//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaServicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GERENTE
    {
        public int CEDULA { get; set; }
        public string ESPECIALIZACION { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
