//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaServicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOARRIENDO
    {
        public int IDPago { get; set; }
        public int IDArriendo { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal Monto { get; set; }
        public bool EstadoPago { get; set; }
    
        public virtual ARRENDAMIENTO ARRENDAMIENTO { get; set; }
    }
}
