//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaServicio.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PROPIEDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPIEDAD()
        {
            this.VENTAs = new HashSet<VENTA>();
        }
    
        public int ID { get; set; }
        public string Direccion { get; set; }
        public int IDCiudad { get; set; }
        public int IdDuenio { get; set; }
        public int TipoPropiedad { get; set; }
        public string Estado { get; set; }
        public decimal Precio { get; set; }
        public Nullable<double> Area { get; set; }
        [JsonIgnore]
        public virtual CIUDAD CIUDAD { get; set; }
        [JsonIgnore]
        public virtual DUENIO DUENIO { get; set; }
        [JsonIgnore]
        public virtual TIPOPROPIEDAD TIPOPROPIEDAD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<VENTA> VENTAs { get; set; }
    }
}
