//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaServicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public int ID { get; set; }
        public int IDClienteComprador { get; set; }
        public int IDEmpleado { get; set; }
        public int IDPropiedad { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal Vlr_comision { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROPIEDAD PROPIEDAD { get; set; }
    }
}
